### PR TITLE
LPS-105380

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
@marco-leo duplicate if statement, not sure if that was intentional, so just combined the two statements to leave logic as is...

**Comment by marco-leo** [comment]
I @hhuijser I think that is an error. @dsitu can you please fix it?

**Comment by marco-leo** [comment]
Is a duplicated statement, we just need one

**Comment by dsitu** [comment]
@marco-leo yep ill send a fix for that

**Comment by hhuijser** [comment]
Thanks guys!

**Comment by marco-leo** [comment]
fix in https://github.com/liferay-commerce/liferay-portal/pull/1522

**Pull request closed without merging**
