### PR TITLE
Commerce 4620 

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
FYI @jpince @vicnate5 @shuyangzhou

**Comment by jpince** [comment]
@marco-leo please make sure to set up your liferay-portal repo for CI... probably need to add CI as a collaborator 
https://grow.liferay.com/people/Pull+Request+Tester+for+Liferay+Developers

**Comment by marco-leo** [comment]
Hey @tinatian can you send please to https://github.com/liferay-commerce/liferay-portal/. is the official lifera-commerce user we use to forward to Brian.
Thanks

**Comment by jpince** [comment]
see https://github.com/liferay-commerce/liferay-portal/pull/62

**Pull request closed without merging**
